[build]
  base = "cookie_run_wiki"
  command = "npm run build"
  publish = "cookie_run_wiki/public"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview]
  command = "npm run build-preview"
