
[build]
  command = "npm install && CI= npm run build"
  publish = "public" 

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview]
  command = "npm run build-preview"
\