const characters = [
    {name: "Gingerbrave", img: "../src/assets/Cookie_Card/Cookie_gingerbrave_card.png", id:"1" , rarity: "Common", class: "Charge", position: "Front", element: "None",},
    {name: "Strawberry", img: "../src/assets/Cookie_Card/Cookie_strawberry_card.png", id:"2" , rarity: "Common", class: "Charge", position: "Front", element: "None",},
    {name: "Wizard", img: "../src/assets/Cookie_Card/Cookie_wizard_card.png", id:"3" ,rarity: "Common", class: "Magic", position: "Middle", element: "None",},
    {name: "Beet", img: "../src/assets/Cookie_Card/Cookie_beet_card.png", id:"4" , rarity: "Common", class: "Ranged", position: "Rear", element: "None",},
    {name: "Angel", img: "../src/assets/Cookie_Card/Cookie_angel_card.png", id:"5" , rarity: "Common", class: "Healing", position: "Rear", element: "None",},
    {name: "Ninja", img: "../src/assets/Cookie_Card/Cookie_ninja_card.png", id:"6" , rarity: "Common", class: "Ambush", position: "Middle", element: "None",},
    {name: "Muscle", img: "../src/assets/Cookie_Card/Cookie_muscle_card.png", id:"7" , rarity: "Common", class: "Charge", position: "Front", element: "None",},
    {name: "Adventurer", img: "../src/assets/Cookie_Card/Cookie_adventurer_card.png", id:"8" , rarity: "Rare", class: "Ambush", position: "Middle", element: "None",},
    {name: "Alchemist", img: "../src/assets/Cookie_Card/Cookie_alchemist_card.png", id:"9" , rarity: "Rare", class: "Bomber", position: "Middle", element: "poison",},
    {name: "Avocado", img: "../src/assets/Cookie_Card/Cookie_avocado_card.png", id:"10" ,rarity: "Rare", class: "Defense", position: "Front", element: "None",},
    {name: "Blackberry", img: "../src/assets/Cookie_Card/Cookie_blackberry_card.png", id:"11" , rarity: "Rare", class: "Magic", position: "Rear", element: "None",},
    {name: "Carrot", img: "../src/assets/Cookie_Card/Cookie_carrot_card.png", id:"12" ,rarity: "Rare", class: "Support", position: "Middle", element: "None",},
    {name: "Cherry", img: "../src/assets/Cookie_Card/Cookie_cherry_card.png", id:"13" , rarity: "Rare", class: "Bomber", position: "Rear", element: "None",},
    {name: "Clover", img: "../src/assets/Cookie_Card/Cookie_clover_card.png", id:"14" ,rarity: "Rare", class: "Support", position: "Rear", element: "None",},
    {name: "Custard", img: "../src/assets/Cookie_Card/Cookie_custard_card.png", id:"15" ,rarity: "Rare", class: "Healing", position: "Rear", element: "None",},
    {name: "Devil", img: "../src/assets/Cookie_Card/Cookie_devil_card.png", id:"215" ,rarity: "Rare", class: "Magic", position: "Middle", element: "None",},
    {name: "Gumball", img: "../src/assets/Cookie_Card/Cookie_gumball_card.png", id:"16" ,rarity: "Rare", class: "Bomber", position: "Rear", element: "None",},
    {name: "Knight", img: "../src/assets/Cookie_Card/Cookie_knight_card.png", id:"17" ,rarity: "Rare", class: "Defense", position: "Front", element: "None",},
    {name: "Onion", img: "../src/assets/Cookie_Card/Cookie_onion_card.png", id:"18" ,rarity: "Rare", class: "Support", position: "Middle", element: "None",},
    {name: "Pancake", img: "../src/assets/Cookie_Card/Cookie_pancake_card.png", id:"19" ,rarity: "Rare", class: "Ambush", position: "Rear", element: "None",},
    {name: "Princess", img: "../src/assets/Cookie_Card/Cookie_princess_card.png", id:"20" ,rarity: "Rare", class: "Charge", position: "Front", element: "None",},
    {name: "Sonic", img: "../src/assets/Cookie_Card/Cookie_sonic_card.png", id:"21" ,rarity: "Special", class: "Ambush", position: "Middle", element: "None",},
    {name: "Tails", img: "../src/assets/Cookie_Card/Cookie_tails_card.png", id:"21" ,rarity: "Special", class: "Ambush", position: "Middle", element: "None",},
    {name: "J-hope", img: "../src/assets/Cookie_Card/Cookie_j-hope_card.png", id:"21" ,rarity: "Special", class: "BTS", position: "Rear", element: "None",},
    {name: "Jimin", img: "../src/assets/Cookie_Card/Cookie_jimin_card.png", id:"21" ,rarity: "Special", class: "BTS", position: "Rear", element: "None",},
    {name: "Jin", img: "../src/assets/Cookie_Card/Cookie_jin_card.png", id:"21" ,rarity: "Special", class: "BTS", position: "Rear", element: "None",},
    {name: "Jung Kook", img: "../src/assets/Cookie_Card/Cookie_jung_kook_card.png", id:"21" ,rarity: "Special", class: "BTS", position: "Rear", element: "None",},
    {name: "RM", img: "../src/assets/Cookie_Card/Cookie_rm_card.png", id:"21" ,rarity: "Special", class: "BTS", position: "Rear", element: "None",},
    {name: "Suga", img: "../src/assets/Cookie_Card/Cookie_suga_card.png", id:"21" ,rarity: "Special", class: "BTS", position: "Rear", element: "None",},
    {name: "V", img: "../src/assets/Cookie_Card/Cookie_v_card.png", id:"21" ,rarity: "Special", class: "BTS", position: "Rear", element: "None",},
    {name: "Snapdragon", img: "../src/assets/Cookie_Card/Cookie_snapdragon_card.png", id:"21" ,rarity: "Special", class: "Support", position: "Rear", element: "None",},
    {name: "Icicle yeti", img: "../src/assets/Cookie_Card/Cookie_icicle_yeti_card.png", id:"21" ,rarity: "Special", class: "Healing", position: "Front", element: "ice",},
    {name: "Affogato", img: "../src/assets/Cookie_Card/Cookie_affogato_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "poison",},
    {name: "Almond", img: "../src/assets/Cookie_Card/Cookie_almond_card.png", id:"21" ,rarity: "Epic", class: "Support", position: "Rear", element: "None",},
    {name: "Black lemonade", img: "../src/assets/Cookie_Card/Cookie_black_lemonade_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "None",},
    {name: "Black raisin", img: "../src/assets/Cookie_Card/Cookie_black_raisin_card.png", id:"21" ,rarity: "Epic", class: "Ambush", position: "Middle", element: "None",},
    {name: "Blueberry pie", img: "../src/assets/Cookie_Card/Cookie_blueberry_pie_card.png", id:"21" ,rarity: "Epic", class: "Magic", position: "Middle", element: "None",},
    {name: "Burnt cheese", img: "../src/assets/Cookie_Card/Cookie_burnt_cheese_card.png", id:"21" ,rarity: "Epic", class: "Charge", position: "Front", element: "earth",},
    {name: "Candy diver", img: "../src/assets/Cookie_Card/Cookie_candy_diver_card.png", id:"21" ,rarity: "Epic", class: "Support", position: "Rear", element: "None",},
    {name: "Captain caviar", img: "../src/assets/Cookie_Card/Cookie_captain_caviar_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "water",},
    {name: "Сaramel arrow", img: "../src/assets/Cookie_Card/Cookie_caramel_arrow_card.png", id:"21" ,rarity: "Epic", class: "Ranged", position: "Front", element: "None",},
    {name: "Carol", img: "../src/assets/Cookie_Card/Cookie_carol_card.png", id:"21" ,rarity: "Epic", class: "Support", position: "Rear", element: "None",},
    {name: "Cherry blossom", img: "../src/assets/Cookie_Card/Cookie_cherry_blossom_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "None",},
    {name: "Chili pepper", img: "../src/assets/Cookie_Card/Cookie_chili_pepper_card.png", id:"21" ,rarity: "Epic", class: "Ambush", position: "Middle", element: "None",},
    {name: "Cocoa", img: "../src/assets/Cookie_Card/Cookie_cocoa_card.png", id:"21" ,rarity: "Epic", class: "Magic", position: "Middle", element: "None",},
    {name: "Cotton", img: "../src/assets/Cookie_Card/Cookie_cotton_card.png", id:"21" ,rarity: "Epic", class: "Charge", position: "Front", element: "earth",},
    {name: "Cream puff", img: "../src/assets/Cookie_Card/Cookie_cream_puff_card.png", id:"21" ,rarity: "Epic", class: "Support", position: "Rear", element: "None",},
    {name: "Cream unicorn", img: "../src/assets/Cookie_Card/Cookie_cream_unicorn_card.png", id:"21" ,rarity: "Epic", class: "Magic", position: "Middle", element: "None",},
    {name: "Crunchy chip ", img: "../src/assets/Cookie_Card/Cookie_crunchy_chip_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "water",},
    {name: "Dark choco", img: "../src/assets/Cookie_Card/Cookie_dark_choco_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "poison",},
    {name: "Eclair", img: "../src/assets/Cookie_Card/Cookie_eclair_card.png", id:"21" ,rarity: "Epic", class: "Support", position: "Rear", element: "None",},
    {name: "Espresso", img: "../src/assets/Cookie_Card/Cookie_espresso_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "None",},
    {name: "Fettuccine", img: "../src/assets/Cookie_Card/Cookie_fettuccine_card.png", id:"21" ,rarity: "Epic", class: "Ambush", position: "Middle", element: "None",},
    {name: "Fig", img: "../src/assets/Cookie_Card/Cookie_fig_card.png", id:"21" ,rarity: "Epic", class: "Magic", position: "Middle", element: "None",},
    {name: "Financier", img: "../src/assets/Cookie_Card/Cookie_financier_card.png", id:"21" ,rarity: "Epic", class: "Charge", position: "Front", element: "earth",},
    {name: "Frilled jellyfish", img: "../src/assets/Cookie_Card/Cookie_frilled_jellyfish_card.png", id:"21" ,rarity: "Epic", class: "Support", position: "Rear", element: "None",},
    {name: "Herb", img: "../src/assets/Cookie_Card/Cookie_herb_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "water",},
    {name: "Affogato", img: "../src/assets/Cookie_Card/Cookie_affogato_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "poison",},
    {name: "Almond", img: "../src/assets/Cookie_Card/Cookie_almond_card.png", id:"21" ,rarity: "Epic", class: "Support", position: "Rear", element: "None",},
    {name: "Black lemonade", img: "../src/assets/Cookie_Card/Cookie_black_lemonade_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "None",},
    {name: "Black raisin", img: "../src/assets/Cookie_Card/Cookie_black_raisin_card.png", id:"21" ,rarity: "Epic", class: "Ambush", position: "Middle", element: "None",},
    {name: "Blueberry pie", img: "../src/assets/Cookie_Card/Cookie_blueberry_pie_card.png", id:"21" ,rarity: "Epic", class: "Magic", position: "Middle", element: "None",},
    {name: "Burnt cheese", img: "../src/assets/Cookie_Card/Cookie_burnt_cheese_card.png", id:"21" ,rarity: "Epic", class: "Charge", position: "Front", element: "earth",},
    {name: "Candy diver", img: "../src/assets/Cookie_Card/Cookie_candy_diver_card.png", id:"21" ,rarity: "Epic", class: "Support", position: "Rear", element: "None",},
    {name: "Captain caviar", img: "../src/assets/Cookie_Card/Cookie_captain_caviar_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "water",},
    {name: "Affogato", img: "../src/assets/Cookie_Card/Cookie_affogato_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "poison",},
    {name: "Almond", img: "../src/assets/Cookie_Card/Cookie_almond_card.png", id:"21" ,rarity: "Epic", class: "Support", position: "Rear", element: "None",},
    {name: "Black lemonade", img: "../src/assets/Cookie_Card/Cookie_black_lemonade_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "None",},
    {name: "Black raisin", img: "../src/assets/Cookie_Card/Cookie_black_raisin_card.png", id:"21" ,rarity: "Epic", class: "Ambush", position: "Middle", element: "None",},
    {name: "Blueberry pie", img: "../src/assets/Cookie_Card/Cookie_blueberry_pie_card.png", id:"21" ,rarity: "Epic", class: "Magic", position: "Middle", element: "None",},
    {name: "Burnt cheese", img: "../src/assets/Cookie_Card/Cookie_burnt_cheese_card.png", id:"21" ,rarity: "Epic", class: "Charge", position: "Front", element: "earth",},
    {name: "Candy diver", img: "../src/assets/Cookie_Card/Cookie_candy_diver_card.png", id:"21" ,rarity: "Epic", class: "Support", position: "Rear", element: "None",},
    {name: "Captain caviar", img: "../src/assets/Cookie_Card/Cookie_captain_caviar_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "water",},
    {name: "Affogato", img: "../src/assets/Cookie_Card/Cookie_affogato_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "poison",},
    {name: "Almond", img: "../src/assets/Cookie_Card/Cookie_almond_card.png", id:"21" ,rarity: "Epic", class: "Support", position: "Rear", element: "None",},
    {name: "Black lemonade", img: "../src/assets/Cookie_Card/Cookie_black_lemonade_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "None",},
    {name: "Black raisin", img: "../src/assets/Cookie_Card/Cookie_black_raisin_card.png", id:"21" ,rarity: "Epic", class: "Ambush", position: "Middle", element: "None",},
    {name: "Blueberry pie", img: "../src/assets/Cookie_Card/Cookie_blueberry_pie_card.png", id:"21" ,rarity: "Epic", class: "Magic", position: "Middle", element: "None",},
    {name: "Burnt cheese", img: "../src/assets/Cookie_Card/Cookie_burnt_cheese_card.png", id:"21" ,rarity: "Epic", class: "Charge", position: "Front", element: "earth",},
    {name: "Candy diver", img: "../src/assets/Cookie_Card/Cookie_candy_diver_card.png", id:"21" ,rarity: "Epic", class: "Support", position: "Rear", element: "None",},
    {name: "Captain caviar", img: "../src/assets/Cookie_Card/Cookie_captain_caviar_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "water",},
    {name: "Affogato", img: "../src/assets/Cookie_Card/Cookie_affogato_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "poison",},
    {name: "Almond", img: "../src/assets/Cookie_Card/Cookie_almond_card.png", id:"21" ,rarity: "Epic", class: "Support", position: "Rear", element: "None",},
    {name: "Black lemonade", img: "../src/assets/Cookie_Card/Cookie_black_lemonade_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "None",},
    {name: "Black raisin", img: "../src/assets/Cookie_Card/Cookie_black_raisin_card.png", id:"21" ,rarity: "Epic", class: "Ambush", position: "Middle", element: "None",},
    {name: "Blueberry pie", img: "../src/assets/Cookie_Card/Cookie_blueberry_pie_card.png", id:"21" ,rarity: "Epic", class: "Magic", position: "Middle", element: "None",},
    {name: "Burnt cheese", img: "../src/assets/Cookie_Card/Cookie_burnt_cheese_card.png", id:"21" ,rarity: "Epic", class: "Charge", position: "Front", element: "earth",},
    {name: "Candy diver", img: "../src/assets/Cookie_Card/Cookie_candy_diver_card.png", id:"21" ,rarity: "Epic", class: "Support", position: "Rear", element: "None",},
    {name: "Captain caviar", img: "../src/assets/Cookie_Card/Cookie_captain_caviar_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "water",},
    {name: "Affogato", img: "../src/assets/Cookie_Card/Cookie_affogato_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "poison",},
    {name: "Almond", img: "../src/assets/Cookie_Card/Cookie_almond_card.png", id:"21" ,rarity: "Epic", class: "Support", position: "Rear", element: "None",},
    {name: "Black lemonade", img: "../src/assets/Cookie_Card/Cookie_black_lemonade_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "None",},
    {name: "Black raisin", img: "../src/assets/Cookie_Card/Cookie_black_raisin_card.png", id:"21" ,rarity: "Epic", class: "Ambush", position: "Middle", element: "None",},
    {name: "Blueberry pie", img: "../src/assets/Cookie_Card/Cookie_blueberry_pie_card.png", id:"21" ,rarity: "Epic", class: "Magic", position: "Middle", element: "None",},
    {name: "Burnt cheese", img: "../src/assets/Cookie_Card/Cookie_burnt_cheese_card.png", id:"21" ,rarity: "Epic", class: "Charge", position: "Front", element: "earth",},
    {name: "Candy diver", img: "../src/assets/Cookie_Card/Cookie_candy_diver_card.png", id:"21" ,rarity: "Epic", class: "Support", position: "Rear", element: "None",},
    {name: "Captain caviar", img: "../src/assets/Cookie_Card/Cookie_captain_caviar_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "water",},
    {name: "Affogato", img: "../src/assets/Cookie_Card/Cookie_affogato_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "poison",},
    {name: "Almond", img: "../src/assets/Cookie_Card/Cookie_almond_card.png", id:"21" ,rarity: "Epic", class: "Support", position: "Rear", element: "None",},
    {name: "Black lemonade", img: "../src/assets/Cookie_Card/Cookie_black_lemonade_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "None",},
    {name: "Black raisin", img: "../src/assets/Cookie_Card/Cookie_black_raisin_card.png", id:"21" ,rarity: "Epic", class: "Ambush", position: "Middle", element: "None",},
    {name: "Capsaicin", img: "../src/assets/Cookie_Card/Cookie_capsaicin_card.png", id:"21" ,rarity: "Super_epic", class: "Ambush", position: "Middle", element: "None",},
    {name: "Capsaicin", img: "../src/assets/Cookie_Card/Cookie_capsaicin_card.png", id:"21" ,rarity: "Super_epic", class: "Ambush", position: "Middle", element: "None",},
    {name: "Capsaicin", img: "../src/assets/Cookie_Card/Cookie_capsaicin_card.png", id:"21" ,rarity: "Super_epic", class: "Ambush", position: "Middle", element: "None",},
    {name: "Capsaicin", img: "../src/assets/Cookie_Card/Cookie_capsaicin_card.png", id:"21" ,rarity: "Super_epic", class: "Ambush", position: "Middle", element: "None",},
    {name: "Capsaicin", img: "../src/assets/Cookie_Card/Cookie_capsaicin_card.png", id:"21" ,rarity: "Super_epic", class: "Ambush", position: "Middle", element: "None",},
    {name: "Capsaicin", img: "../src/assets/Cookie_Card/Cookie_capsaicin_card.png", id:"21" ,rarity: "Super_epic", class: "Ambush", position: "Middle", element: "None",},
    {name: "Capsaicin", img: "../src/assets/Cookie_Card/Cookie_capsaicin_card.png", id:"21" ,rarity: "Super_epic", class: "Ambush", position: "Middle", element: "None",},
    {name: "Black pearl", img: "../src/assets/Cookie_Card/Cookie_black_pearl_card.png", id:"21" ,rarity: "Legendary", class: "Ambush", position: "Middle", element: "None",},
    {name: "Black pearl", img: "../src/assets/Cookie_Card/Cookie_black_pearl_card.png", id:"21" ,rarity: "Legendary", class: "Ambush", position: "Middle", element: "None",},
    {name: "Black pearl", img: "../src/assets/Cookie_Card/Cookie_black_pearl_card.png", id:"21" ,rarity: "Legendary", class: "Ambush", position: "Middle", element: "None",},
    {name: "Black pearl", img: "../src/assets/Cookie_Card/Cookie_black_pearl_card.png", id:"21" ,rarity: "Legendary", class: "Ambush", position: "Middle", element: "None",},
    {name: "Pitaya dragon", img: "../src/assets/Cookie_Card/Cookie_pitaya_dragon_card.png", id:"21" ,rarity: "Dragon", class: "Charge", position: "Front", element: "Fire",},
    {name: "Golden cheese", img: "../src/assets/Cookie_Card/Cookie_golden_cheese_card.png", id:"21" ,rarity: "Ancient", class: "Ranged", position: "Middle", element: "earth",},
    {name: "Golden cheese", img: "../src/assets/Cookie_Card/Cookie_golden_cheese_card.png", id:"21" ,rarity: "Ancient", class: "Ranged", position: "Middle", element: "None",},
    {name: "Golden cheese", img: "../src/assets/Cookie_Card/Cookie_golden_cheese_card.png", id:"21" ,rarity: "Ancient", class: "Ranged", position: "Middle", element: "None",},
    {name: "Golden cheese", img: "../src/assets/Cookie_Card/Cookie_golden_cheese_card.png", id:"21" ,rarity: "Ancient", class: "Ranged", position: "Middle", element: "None",},
    {name: "Aladdin", img: "../src/assets/Cookie_Card/Cookie_aladdin_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Aladdin", img: "../src/assets/Cookie_Card/Cookie_aladdin_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Aladdin", img: "../src/assets/Cookie_Card/Cookie_aladdin_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Aladdin", img: "../src/assets/Cookie_Card/Cookie_aladdin_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Aladdin", img: "../src/assets/Cookie_Card/Cookie_aladdin_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Aladdin", img: "../src/assets/Cookie_Card/Cookie_aladdin_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Aladdin", img: "../src/assets/Cookie_Card/Cookie_aladdin_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Aladdin", img: "../src/assets/Cookie_Card/Cookie_aladdin_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Aladdin", img: "../src/assets/Cookie_Card/Cookie_aladdin_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Aladdin", img: "../src/assets/Cookie_Card/Cookie_aladdin_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Aladdin", img: "../src/assets/Cookie_Card/Cookie_aladdin_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Aladdin", img: "../src/assets/Cookie_Card/Cookie_aladdin_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Aladdin", img: "../src/assets/Cookie_Card/Cookie_aladdin_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Aladdin", img: "../src/assets/Cookie_Card/Cookie_aladdin_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Aladdin", img: "../src/assets/Cookie_Card/Cookie_aladdin_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Aladdin", img: "../src/assets/Cookie_Card/Cookie_aladdin_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Aladdin", img: "../src/assets/Cookie_Card/Cookie_aladdin_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Aladdin", img: "../src/assets/Cookie_Card/Cookie_aladdin_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Aladdin", img: "../src/assets/Cookie_Card/Cookie_aladdin_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Aladdin", img: "../src/assets/Cookie_Card/Cookie_aladdin_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Aladdin", img: "../src/assets/Cookie_Card/Cookie_aladdin_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Aladdin", img: "../src/assets/Cookie_Card/Cookie_aladdin_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Aladdin", img: "../src/assets/Cookie_Card/Cookie_aladdin_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
  ];

  export default characters;
