const characters = [
    {name: "Gingerbrave", img: "../src/assets/Cookie_Card/Cookie_gingerbrave_card.png", id:"1" , rarity: "Common", class: "Charge", position: "Front", element: "None",},
    {name: "Strawberry", img: "../src/assets/Cookie_Card/Cookie_strawberry_card.png", id:"2" , rarity: "Common", class: "Defense", position: "Front", element: "None",},
    {name: "Wizard", img: "../src/assets/Cookie_Card/Cookie_wizard_card.png", id:"3" ,rarity: "Common", class: "Magic", position: "Middle", element: "None",},
    {name: "Beet", img: "../src/assets/Cookie_Card/Cookie_beet_card.png", id:"4" , rarity: "Common", class: "Ranged", position: "Rear", element: "None",},
    {name: "Angel", img: "../src/assets/Cookie_Card/Cookie_angel_card.png", id:"5" , rarity: "Common", class: "Healing", position: "Rear", element: "None",},
    {name: "Ninja", img: "../src/assets/Cookie_Card/Cookie_ninja_card.png", id:"6" , rarity: "Common", class: "Ambush", position: "Middle", element: "None",},
    {name: "Muscle", img: "../src/assets/Cookie_Card/Cookie_muscle_card.png", id:"7" , rarity: "Common", class: "Charge", position: "Front", element: "None",},
    {name: "Adventurer", img: "../src/assets/Cookie_Card/Cookie_adventurer_card.png", id:"8" , rarity: "Rare", class: "Ambush", position: "Middle", element: "None",},
    {name: "Alchemist", img: "../src/assets/Cookie_Card/Cookie_alchemist_card.png", id:"9" , rarity: "Rare", class: "Bomber", position: "Middle", element: "poison",},
    {name: "Avocado", img: "../src/assets/Cookie_Card/Cookie_avocado_card.png", id:"10" ,rarity: "Rare", class: "Defense", position: "Front", element: "None",},
    {name: "Blackberry", img: "../src/assets/Cookie_Card/Cookie_blackberry_card.png", id:"11" , rarity: "Rare", class: "Magic", position: "Rear", element: "None",},
    {name: "Carrot", img: "../src/assets/Cookie_Card/Cookie_carrot_card.png", id:"12" ,rarity: "Rare", class: "Support", position: "Middle", element: "None",},
    {name: "Cherry", img: "../src/assets/Cookie_Card/Cookie_cherry_card.png", id:"13" , rarity: "Rare", class: "Bomber", position: "Rear", element: "None",},
    {name: "Clover", img: "../src/assets/Cookie_Card/Cookie_clover_card.png", id:"14" ,rarity: "Rare", class: "Support", position: "Rear", element: "None",},
    {name: "Custard", img: "../src/assets/Cookie_Card/Cookie_custard_card.png", id:"15" ,rarity: "Rare", class: "Healing", position: "Rear", element: "None",},
    {name: "Devil", img: "../src/assets/Cookie_Card/Cookie_devil_card.png", id:"42" ,rarity: "Rare", class: "Magic", position: "Middle", element: "None",},
    {name: "Gumball", img: "../src/assets/Cookie_Card/Cookie_gumball_card.png", id:"16" ,rarity: "Rare", class: "Bomber", position: "Rear", element: "None",},
    {name: "Knight", img: "../src/assets/Cookie_Card/Cookie_knight_card.png", id:"17" ,rarity: "Rare", class: "Defense", position: "Front", element: "None",},
    {name: "Onion", img: "../src/assets/Cookie_Card/Cookie_onion_card.png", id:"18" ,rarity: "Rare", class: "Support", position: "Middle", element: "None",},
    {name: "Pancake", img: "../src/assets/Cookie_Card/Cookie_pancake_card.png", id:"19" ,rarity: "Rare", class: "Ambush", position: "Rear", element: "None",},
    {name: "Princess", img: "../src/assets/Cookie_Card/Cookie_princess_card.png", id:"20" ,rarity: "Rare", class: "Charge", position: "Front", element: "None",},
    {name: "Sonic", img: "../src/assets/Cookie_Card/Cookie_sonic_card.png", id:"21" ,rarity: "Special", class: "Ambush", position: "Middle", element: "None",},
    {name: "Tails", img: "../src/assets/Cookie_Card/Cookie_tails_card.png", id:"21" ,rarity: "Special", class: "Ambush", position: "Middle", element: "None",},
    {name: "J-hope", img: "../src/assets/Cookie_Card/Cookie_j-hope_card.png", id:"21" ,rarity: "Special", class: "BTS", position: "Rear", element: "None",},
    {name: "Jimin", img: "../src/assets/Cookie_Card/Cookie_jimin_card.png", id:"21" ,rarity: "Special", class: "BTS", position: "Rear", element: "None",},
    {name: "Jin", img: "../src/assets/Cookie_Card/Cookie_jin_card.png", id:"21" ,rarity: "Special", class: "BTS", position: "Rear", element: "None",},
    {name: "Jung Kook", img: "../src/assets/Cookie_Card/Cookie_jung_kook_card.png", id:"21" ,rarity: "Special", class: "BTS", position: "Rear", element: "None",},
    {name: "RM", img: "../src/assets/Cookie_Card/Cookie_rm_card.png", id:"21" ,rarity: "Special", class: "BTS", position: "Rear", element: "None",},
    {name: "Suga", img: "../src/assets/Cookie_Card/Cookie_suga_card.png", id:"21" ,rarity: "Special", class: "BTS", position: "Rear", element: "None",},
    {name: "V", img: "../src/assets/Cookie_Card/Cookie_v_card.png", id:"21" ,rarity: "Special", class: "BTS", position: "Rear", element: "None",},
    {name: "Snapdragon", img: "../src/assets/Cookie_Card/Cookie_snapdragon_card.png", id:"21" ,rarity: "Special", class: "Support", position: "Rear", element: "None",},
    {name: "Icicle yeti", img: "../src/assets/Cookie_Card/Cookie_icicle_yeti_card.png", id:"21" ,rarity: "Special", class: "Healing", position: "Front", element: "ice",},
    {name: "Affogato", img: "../src/assets/Cookie_Card/Cookie_affogato_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "poison",},
    {name: "Almond", img: "../src/assets/Cookie_Card/Cookie_almond_card.png", id:"21" ,rarity: "Epic", class: "Support", position: "Rear", element: "None",},
    {name: "Black lemonade", img: "../src/assets/Cookie_Card/Cookie_black_lemonade_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "None",},
    {name: "Black raisin", img: "../src/assets/Cookie_Card/Cookie_black_raisin_card.png", id:"21" ,rarity: "Epic", class: "Ambush", position: "Middle", element: "None",},
    {name: "Blueberry pie", img: "../src/assets/Cookie_Card/Cookie_blueberry_pie_card.png", id:"21" ,rarity: "Epic", class: "Magic", position: "Middle", element: "None",},
    {name: "Burnt cheese", img: "../src/assets/Cookie_Card/Cookie_burnt_cheese_card.png", id:"21" ,rarity: "Epic", class: "Charge", position: "Front", element: "earth",},
    {name: "Candy diver", img: "../src/assets/Cookie_Card/Cookie_candy_diver_card.png", id:"21" ,rarity: "Epic", class: "Support", position: "Rear", element: "None",},
    {name: "Captain caviar", img: "../src/assets/Cookie_Card/Cookie_captain_caviar_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "water",},
    {name: "Caramel arrow", img: "../src/assets/Cookie_Card/Cookie_caramel_arrow_card.png", id:"21" ,rarity: "Epic", class: "Ranged", position: "Front", element: "None",},
    {name: "Carol", img: "../src/assets/Cookie_Card/Cookie_carol_card.png", id:"21" ,rarity: "Epic", class: "Healing", position: "Rear", element: "None",},
    {name: "Cherry blossom", img: "../src/assets/Cookie_Card/Cookie_cherry_blossom_card.png", id:"21" ,rarity: "Epic", class: "Ambush", position: "Middle", element: "None",},
    {name: "Chili pepper", img: "../src/assets/Cookie_Card/Cookie_chili_pepper_card.png", id:"22" ,rarity: "Epic", class: "Ambush", position: "Rear", element: "fire",},
    {name: "Cocoa", img: "../src/assets/Cookie_Card/Cookie_cocoa_card.png", id:"21" ,rarity: "Epic", class: "Defense", position: "Front", element: "None",},
    {name: "Cotton", img: "../src/assets/Cookie_Card/Cookie_cotton_card.png", id:"21" ,rarity: "Epic", class: "Ranged", position: "Rear", element: "None",},
    {name: "Cream puff", img: "../src/assets/Cookie_Card/Cookie_cream_puff_card.png", id:"21" ,rarity: "Epic", class: "Support", position: "Rear", element: "light",},
    {name: "Cream unicorn", img: "../src/assets/Cookie_Card/Cookie_cream_unicorn_card.png", id:"21" ,rarity: "Epic", class: "Healing", position: "Rear", element: "None",},
    {name: "Crunchy chip ", img: "../src/assets/Cookie_Card/Cookie_crunchy_chip_card.png", id:"21" ,rarity: "Epic", class: "Charge", position: "Front", element: "None",},
    {name: "Dark choco", img: "../src/assets/Cookie_Card/Cookie_dark_choco_card.png", id:"21" ,rarity: "Epic", class: "Charge", position: "Front", element: "None",},
    {name: "Eclair", img: "../src/assets/Cookie_Card/Cookie_eclair_card.png", id:"21" ,rarity: "Epic", class: "Support", position: "Middle", element: "None",},
    {name: "Espresso", img: "../src/assets/Cookie_Card/Cookie_espresso_card.png", id:"21" ,rarity: "Epic", class: "Magic", position: "Middle", element: "None",},
    {name: "Fettuccine", img: "../src/assets/Cookie_Card/Cookie_fettuccine_card.png", id:"21" ,rarity: "Epic", class: "Defense", position: "Front", element: "earth",},
    {name: "Fig", img: "../src/assets/Cookie_Card/Cookie_fig_card.png", id:"21" ,rarity: "Epic", class: "Support", position: "Middle", element: "None",},
    {name: "Financier", img: "../src/assets/Cookie_Card/Cookie_financier_card.png", id:"21" ,rarity: "Epic", class: "Defense", position: "Front", element: "light",},
    {name: "Frilled jellyfish", img: "../src/assets/Cookie_Card/Cookie_frilled_jellyfish_card.png", id:"21" ,rarity: "Epic", class: "Support", position: "Middle", element: "water",},
    {name: "Herb", img: "../src/assets/Cookie_Card/Cookie_herb_card.png", id:"29" ,rarity: "Epic", class: "Healing", position: "Rear", element: "None",},
    {name: "Kouign amann", img: "../src/assets/Cookie_Card/Cookie_kouign-amann_card.png", id:"21" ,rarity: "Epic", class: "Defense", position: "Front", element: "light",},
    {name: "Kumiho", img: "../src/assets/Cookie_Card/Cookie_kumiho_card.png", id:"21" ,rarity: "Epic", class: "Charge", position: "Front", element: "None",},
    {name: "Latte", img: "../src/assets/Cookie_Card/Cookie_latte_card.png", id:"21" ,rarity: "Epic", class: "Magic", position: "Middle", element: "None",},
    {name: "Licorice", img: "../src/assets/Cookie_Card/Cookie_licorice_card.png", id:"25" ,rarity: "Epic", class: "Magic", position: "Middle", element: "poison",},
    {name: "Lilac", img: "../src/assets/Cookie_Card/Cookie_lilac_card.png", id:"21" ,rarity: "Epic", class: "Support", position: "Middle", element: "None",},
    {name: "Macaron", img: "../src/assets/Cookie_Card/Cookie_macaron_card.png", id:"21" ,rarity: "Epic", class: "Magic", position: "Middle", element: "None",},
    {name: "Madeleine", img: "../src/assets/Cookie_Card/Cookie_madeleine_card.png", id:"21" ,rarity: "Epic", class: "Defense", position: "Front", element: "light",},
    {name: "Mala sauce", img: "../src/assets/Cookie_Card/Cookie_mala_sauce_card.png", id:"21" ,rarity: "Epic", class: "Charge", position: "Front", element: "fire",},
    {name: "Mango", img: "../src/assets/Cookie_Card/Cookie_mango_card.png", id:"21" ,rarity: "Epic", class: "Magic", position: "Middle", element: "water",},
    {name: "Milk", img: "../src/assets/Cookie_Card/Cookie_milk_card.png", id:"32" ,rarity: "Epic", class: "Defense", position: "Front", element: "None",},
    {name: "Milky way", img: "../src/assets/Cookie_Card/Cookie_milky_way_card.png", id:"21" ,rarity: "Epic", class: "Charge", position: "Front", element: "None",},
    {name: "Mint choco", img: "../src/assets/Cookie_Card/Cookie_mint_choco_card.png", id:"27" ,rarity: "Epic", class: "Support", position: "Rear", element: "None",},
    {name: "Moon rabbit", img: "../src/assets/Cookie_Card/Cookie_moon_rabbit_card.png", id:"21" ,rarity: "Epic", class: "Defense", position: "Front", element: "None",},
    {name: "Mozzarella", img: "../src/assets/Cookie_Card/Cookie_mozzarella_card.png", id:"105" ,rarity: "Epic", class: "Magic", position: "Middle", element: "earth",},
    {name: "Olive", img: "../src/assets/Cookie_Card/Cookie_olive_card.png", id:"21" ,rarity: "Epic", class: "Support", position: "Rear", element: "earth",},
    {name: "Parfait", img: "../src/assets/Cookie_Card/Cookie_parfait_card.png", id:"21" ,rarity: "Epic", class: "Support", position: "Rear", element: "None",},
    {name: "Pastry", img: "../src/assets/Cookie_Card/Cookie_pastry_card.png", id:"21" ,rarity: "Epic", class: "Ranged", position: "Rear", element: "None",},
    {name: "Peppermint", img: "../src/assets/Cookie_Card/Cookie_peppermint_card.png", id:"21" ,rarity: "Epic", class: "Support", position: "Rear", element: "water",},
    {name: "Pinecone", img: "../src/assets/Cookie_Card/Cookie_pinecone_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Front", element: "ice",},
    {name: "Poison mushroom", img: "../src/assets/Cookie_Card/Cookie_poison_mushroom_card.png", id:"23" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "poison",},
    {name: "Pomegranate", img: "../src/assets/Cookie_Card/Cookie_pomegranate_card.png", id:"24" ,rarity: "Epic", class: "Support", position: "Middle", element: "None",},
    {name: "Prophet", img: "../src/assets/Cookie_Card/Cookie_prophet_card.png", id:"21" ,rarity: "Epic", class: "Support", position: "Rear", element: "None",},
    {name: "Prune juice", img: "../src/assets/Cookie_Card/Cookie_prune_juice_card.png", id:"21" ,rarity: "Epic", class: "Bomber", position: "Middle", element: "poison",},
    {name: "Pumpkin pie", img: "../src/assets/Cookie_Card/Cookie_pumpkin_pie_card.png", id:"21" ,rarity: "Epic", class: "Magic", position: "Middle", element: "None",},
    {name: "Purple yam", img: "../src/assets/Cookie_Card/Cookie_purple_yam_card.png", id:"26" ,rarity: "Epic", class: "Charge", position: "Front", element: "None",},
    {name: "Raspberry", img: "../src/assets/Cookie_Card/Cookie_raspberry_card.png", id:"21" ,rarity: "Epic", class: "Charge", position: "Front", element: "None",},
    {name: "Red velvet", img: "../src/assets/Cookie_Card/Cookie_red_velvet_card.png", id:"21" ,rarity: "Epic", class: "Charge", position: "Front", element: "None",},
    {name: "Rockstar", img: "../src/assets/Cookie_Card/Cookie_rockstar_card.png", id:"21" ,rarity: "Epic", class: "Healing", position: "Middle", element: "None",},
    {name: "Royal margarine", img: "../src/assets/Cookie_Card/Cookie_royal_margarine_card.png", id:"21" ,rarity: "Epic", class: "Ambush", position: "Middle", element: "poison",},
    {name: "Rye", img: "../src/assets/Cookie_Card/Cookie_rye_card.png", id:"21" ,rarity: "Epic", class: "Ranged", position: "Rear", element: "fire",},
    {name: "Schwarzwalder", img: "../src/assets/Cookie_Card/Cookie_schwarzwalder_card.png", id:"21" ,rarity: "Epic", class: "Charge", position: "Front", element: "None",},
    {name: "Snow sugar", img: "../src/assets/Cookie_Card/Cookie_snow_sugar_card.png", id:"21" ,rarity: "Epic", class: "Magic", position: "Middle", element: "ice",},
    {name: "Sorbet shark", img: "../src/assets/Cookie_Card/Cookie_sorbet_shark_card.png", id:"21" ,rarity: "Epic", class: "Ambush", position: "Middle", element: "water",},
    {name: "Space doughnut", img: "../src/assets/Cookie_Card/Cookie_space_doughnut_card.png", id:"21" ,rarity: "Epic", class: "Charge", position: "Rear", element: "None",},
    {name: "Sparkling", img: "../src/assets/Cookie_Card/Cookie_sparkling_card.png", id:"28" ,rarity: "Epic", class: "Healing", position: "Rear", element: "None",},
    {name: "Squid ink", img: "../src/assets/Cookie_Card/Cookie_squid_ink_card.png", id:"21" ,rarity: "Epic", class: "Magic", position: "Middle", element: "water",},
    {name: "Strawberry crepe", img: "../src/assets/Cookie_Card/Cookie_strawberry_crepe_card.png", id:"21" ,rarity: "Epic", class: "Defense", position: "Front", element: "None",},
    {name: "Tarte tatin", img: "../src/assets/Cookie_Card/Cookie_tarte_tatin_card.png", id:"21" ,rarity: "Epic", class: "Ranged", position: "Rear", element: "fire",},
    {name: "Tea knight", img: "../src/assets/Cookie_Card/Cookie_tea_knight_card.png", id:"21" ,rarity: "Epic", class: "Charge", position: "Front", element: "None",},
    {name: "Tiger lily", img: "../src/assets/Cookie_Card/Cookie_tiger_lily_card.png", id:"33" ,rarity: "Epic", class: "Ranged", position: "Rear", element: "None",},
    {name: "Twizzly gummy", img: "../src/assets/Cookie_Card/Cookie_twizzly_gummy_card.png", id:"21" ,rarity: "Epic", class: "Ranged", position: "Rear", element: "None",},
    {name: "Vampire", img: "../src/assets/Cookie_Card/Cookie_vampire_card.png", id:"31" ,rarity: "Epic", class: "Ambush", position: "Rear", element: "None",},
    {name: "Werewolf", img: "../src/assets/Cookie_Card/Cookie_werewolf_card.png", id:"30" ,rarity: "Epic", class: "Charge", position: "Front", element: "None",},
    {name: "Wildberry", img: "../src/assets/Cookie_Card/Cookie_wildberry_card.png", id:"21" ,rarity: "Epic", class: "Defense", position: "Front", element: "None",},
    {name: "Capsaicin", img: "../src/assets/Cookie_Card/Cookie_capsaicin_card.png", id:"21" ,rarity: "Super_epic", class: "Charge", position: "Front", element: "fire",},
    {name: "Clotted cream", img: "../src/assets/Cookie_Card/Cookie_clotted_cream_card.png", id:"21" ,rarity: "Super_epic", class: "Magic", position: "Middle", element: "light",},
    {name: "Crimson coral", img: "../src/assets/Cookie_Card/Cookie_crimson_coral_card.png", id:"21" ,rarity: "Super_epic", class: "Defense", position: "Front", element: "water",},
    {name: "Oyster", img: "../src/assets/Cookie_Card/Cookie_oyster_card.png", id:"21" ,rarity: "Super_epic", class: "Support", position: "Rear", element: "None",},
    {name: "Sherbet", img: "../src/assets/Cookie_Card/Cookie_sherbet_card.png", id:"21" ,rarity: "Super_epic", class: "Ranged", position: "Middle", element: "ice",},
    {name: "Shining glitter", img: "../src/assets/Cookie_Card/Cookie_shining_glitter_card.png", id:"21" ,rarity: "Super_epic", class: "Magic", position: "Middle", element: "None",},
    {name: "Stardust", img: "../src/assets/Cookie_Card/Cookie_stardust_card.png", id:"21" ,rarity: "Super_epic", class: "Ambush", position: "Middle", element: "None",},
    {name: "Black pearl", img: "../src/assets/Cookie_Card/Cookie_black_pearl_card.png", id:"21" ,rarity: "Legendary", class: "Ambush", position: "Middle", element: "water",},
    {name: "Frost queen", img: "../src/assets/Cookie_Card/Cookie_frost_queen_card.png", id:"21" ,rarity: "Legendary", class: "Magic", position: "Middle", element: "ice",},
    {name: "Moonlight", img: "../src/assets/Cookie_Card/Cookie_moonlight_card.png", id:"21" ,rarity: "Legendary", class: "Magic", position: "Middle", element: "None",},
    {name: "Sea fairy", img: "../src/assets/Cookie_Card/Cookie_sea_fairy_card.png", id:"21" ,rarity: "Legendary", class: "Bomber", position: "Middle", element: "water",},
    {name: "Pitaya dragon", img: "../src/assets/Cookie_Card/Cookie_pitaya_dragon_card.png", id:"21" ,rarity: "Dragon", class: "Charge", position: "Front", element: "fire",},
    {name: "Dark Cacao", img: "../src/assets/Cookie_Card/Cookie_dark_cacao_card.png", id:"21" ,rarity: "Ancient", class: "Charge", position: "Front", element: "None",},
    {name: "Golden cheese", img: "../src/assets/Cookie_Card/Cookie_golden_cheese_card.png", id:"21" ,rarity: "Ancient", class: "Ranged", position: "Middle", element: "earth",},
    {name: "Hollyberry", img: "../src/assets/Cookie_Card/Cookie_hollyberry_card.png", id:"21" ,rarity: "Ancient", class: "Defense", position: "Front", element: "None",},
    {name: "Pure vanilla", img: "../src/assets/Cookie_Card/Cookie_pure_vanilla_card.png", id:"21" ,rarity: "Ancient", class: "Healing", position: "Rear", element: "None",},
    {name: "Aladdin", img: "../src/assets/Cookie_Card/Cookie_aladdin_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Alice", img: "../src/assets/Cookie_Card/Cookie_alice_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Ariel", img: "../src/assets/Cookie_Card/Cookie_ariel_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Beast", img: "../src/assets/Cookie_Card/Cookie_beast_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Belle", img: "../src/assets/Cookie_Card/Cookie_belle_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Cinderella", img: "../src/assets/Cookie_Card/Cookie_cinderella_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Daisy duck", img: "../src/assets/Cookie_Card/Cookie_daisy_duck_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Donald duck", img: "../src/assets/Cookie_Card/Cookie_donald_duck_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Goofy", img: "../src/assets/Cookie_Card/Cookie_goofy_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Jasmine", img: "../src/assets/Cookie_Card/Cookie_jasmine_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Lilo", img: "../src/assets/Cookie_Card/Cookie_lilo_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Mickey mouse", img: "../src/assets/Cookie_Card/Cookie_mickey_mouse_card.png", id:"100" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Minnie mouse", img: "../src/assets/Cookie_Card/Cookie_minnie_mouse_card.png", id:"100" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Mulan", img: "../src/assets/Cookie_Card/Cookie_mulan_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Peter pan", img: "../src/assets/Cookie_Card/Cookie_peter_pan_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Pocahontas", img: "../src/assets/Cookie_Card/Cookie_pocahontas_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Princess aurora", img: "../src/assets/Cookie_Card/Cookie_princess_aurora_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Snow white", img: "../src/assets/Cookie_Card/Cookie_snow_white_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Stitch", img: "../src/assets/Cookie_Card/Cookie_stitch_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Tinker bell", img: "../src/assets/Cookie_Card/Cookie_tinker_bell_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Aquamarine", img: "../src/assets/Cookie_Card/Cookie_aquamarine_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Gold citrine", img: "../src/assets/Cookie_Card/Cookie_gold_citrine_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
    {name: "Mystic opal", img: "../src/assets/Cookie_Card/Cookie_mystic_opal_card.png", id:"21" ,rarity: "Guest", class: " ", position: " ", element: " ",},
  ];

  export default characters;